### PR TITLE
Free source code of Flappy Bird Game

### PR DESCRIPTION
**Pull request by Rimjhim-Dey**

### CODE REVIEW

**Comment by Rimjhim-Dey** [comment]
Accept my Pull Request please!!

**Comment by Lau-Tsz-Yueng** [comment]
Hi, yeah i have already accepted your pull request~ obiviously you are the first one who commits my github so far lol
________________________________
发件人: Rimjhim-Dey <notifications@github.com>
发送时间: 2020年10月1日 14:17
收件人: Lau-Tsz-Yueng/Flappy_bird <Flappy_bird@noreply.github.com>
抄送: Ziyang Liu <ao18669@bristol.ac.uk>; State change <state_change@noreply.github.com>
主题: Re: [Lau-Tsz-Yueng/Flappy_bird] Free source code of Flappy Bird Game (#1)


Accept my Pull Request please!!

―

**Comment by Rimjhim-Dey** [comment]
Thanks a lot for accepting it. I will try my best to contribute more so that it helps you. And your codes are awesome I must say.

**Comment by Lau-Tsz-Yueng** [comment]
LOL appreciate it, man. If you want more communication you could follow me on WeChat if you want, my number is Leonardo-SP. Unfortunately, i could not use Facebook because of the web strictions.
________________________________
发件人: Rimjhim-Dey <notifications@github.com>
发送时间: 2020年10月1日 15:50
收件人: Lau-Tsz-Yueng/Flappy_bird <Flappy_bird@noreply.github.com>
抄送: Ziyang Liu <ao18669@bristol.ac.uk>; State change <state_change@noreply.github.com>
主题: Re: [Lau-Tsz-Yueng/Flappy_bird] Free source code of Flappy Bird Game (#1)


Thanks a lot for accepting it. I will try my best to contribute more so that it helps you. And your codes are awesome I must say.

―

**Pull request merged**
